/**
 * BrowOS WebAssembly Spatial Physics Acceleration Engine
 * Offloads uniform-grid broadphase hashing, cylinder/box resolution, ground queries,
 * and high-performance O(N^2) pairwise entity separation (pedestrians & vehicles)
 * into a compiled WebAssembly linear-memory pipeline with zero JavaScript GC overhead.
 */
(function(root) {
    'use strict';

    // Embedded WebAssembly binary for instant zero-latency initialization
    const WASM_BASE64 = 'AGFzbQEAAAABZBBgA39/fwF/YAJ/fwF/YAJ/fwBgA399fQBgAX8AYAAAYAN/f38AYAABfWAAAX9gAX8Bf2AEfX19fQF9YAN9fX0Bf2AFfX19fX0Bf2AHf319fX19fQBgBH9/f38Bf2AEf39/fwADRUQDBAUGBwcICAgICAgICAkICAgICAgICgsFDA0EAgIFAgYBBA4BDgIFDwUJAgICBAQEBAECAgYPBAIAAQACAgECAgICAgQFAXABEhIFAwEAGgYJAX8BQYCAwAALB+oDHAZtZW1vcnkCABpiYXRjaF9zb2x2ZV9wZWRfc2VwYXJhdGlvbgAAHmJhdGNoX3NvbHZlX3ZlaGljbGVfc2VwYXJhdGlvbgABCmJ1aWxkX2dyaWQAAg1nZXRfb3V0X3Bvc194AAQNZ2V0X291dF9wb3NfegAFEmdldF9wZWRfYWN0aXZlX3B0cgAGEWdldF9wZWRfc2VwX3hfcHRyAAcRZ2V0X3BlZF9zZXBfel9wdHIACA5nZXRfcGVkX3Z4X3B0cgAJDmdldF9wZWRfdnpfcHRyAAoNZ2V0X3BlZF94X3B0cgALDWdldF9wZWRfeV9wdHIADA1nZXRfcGVkX3pfcHRyAA0KZ2V0X3Jlc3VsdAAOEGdldF9yZXN1bHRfY291bnQADxJnZXRfdmVoX2FjdGl2ZV9wdHIAEA5nZXRfdmVoX2hwX3B0cgAREmdldF92ZWhfbGVuZ3RoX3B0cgASEWdldF92ZWhfc3BlZWRfcHRyABMNZ2V0X3ZlaF94X3B0cgAUDWdldF92ZWhfel9wdHIAFQlncm91bmRfYXQAFgxxdWVyeV9jaXJjbGUAFwVyZXNldAAYDnJlc29sdmVfY2lyY2xlABkMc2V0X2NvbGxpZGVyABoRc2V0X251bV9jb2xsaWRlcnMAGwkXAQBBAQsRJCE3OTo7Pj9AQTAyMzQrLDgKso4BRK0EBAV/An0DfwN9AkAgAEUNAEEAIQMCQCAAQYABIABBgAFJGyIEQQJ0IgBFIgUNAEH8jeWAAEEAIAD8CwALAkAgBQ0AQfyR5YAAQQAgAPwLAAtBACEGA0AgBiIHQQFqIQYCQCAHLQDsh8CAAEUNACAHQQJ0IgAqAvS12IAAIQggACoC9K3YgAAhCQJAIAYgBE8NACAAQfyR5YAAaiEKIABB/I3lgABqIQsgAyEAIAYhBQNAIAUiDEEBaiEFAkAgDEHsh8CAAGotAABFDQAgCSAAQfit2IAAaioCAJMiDSANlCAIIABB+LXYgABqKgIAkyIOIA6UkiIPQ12PBkBfRQ0AIA9DvTeGNWBFDQAgCiANQ5qZuT8gD5EiD5NDmpm5P5UgD5UiD5QiDUMAAAA/lCAOIA+UIg5D17NdP5SSIg8gCioCAJI4AgAgCyANQ9ezXT+UIA5DAAAAP5STIg0gCyoCAJI4AgAgAEGAkuWAAGoiDCAMKgIAIA+TOAIAIABBgI7lgABqIgwgDCoCACANkzgCAAsgAEEEaiEAIAQgBUcNAAsLIAkgAZMiDSANlCAIIAKTIg4gDpSSIg9DzcyMQF1FDQAgD0O9N4Y1XkUNACAHQQJ0IgAgDUNmZgZAIA+RIg+TQ2ZmBkCVIA+VQ5qZ2T+UIg+UIAAqAvyN5YAAkjgC/I3lgAAgACAOIA+UIAAqAvyR5YAAkjgC/JHlgAALIANBBGohAyAGIARHDQALCwvvAwYFfwN9BH8BfQF/A30CQCAARQ0AIABBgAEgAEGAAUkbIQFBACECQQAhAwNAIAMiAEEBaiEDAkAgAC0A7IjAgABFDQAgAyABTw0AIABBAnQiAEH0vdiAAGohBCAAQfS52IAAaiEFIAAqAuyJ0IAAIQYgACoC9L3YgAAhByAAKgL0udiAACEIIABB9MnYgABqIQkgAEH8leWAAGohCiACIQAgAyELA0ACQCALQeyIwIAAai0AAEUNACAAQfi52IAAaiIMKgIAIAiTIg0gDZQgAEH4vdiAAGoiDioCACAHkyIPIA+UkiIQQ703hjVdDQAgECAGIABB8InQgABqKgIAkkMK16M+lCIRIBGUXg0AIAQgBCoCACAPIBCRIhCVIBEgEJNDAAAAP5QiD5QiEZM4AgAgBSAFKgIAIA0gEJUgD5QiDZM4AgAgDiARIA4qAgCSOAIAIAwgDSAMKgIAkjgCACAKKgIAIg0gAEGAluWAAGoiDCoCACIPk4siEEMAAABBXkUNACAKIA9DmpkZP5Q4AgAgCSAJKgIAIBBDzczMPpQiD5M4AgAgDCANQ5qZGT+UOAIAIABB+MnYgABqIgwgDCoCACAPkzgCAAsgAEEEaiEAIAEgC0EBaiILRw0ACwsgAkEEaiECIAMgAUcNAAsLC6kDAwR/An0Kf0EAIQBB9M3kgABBAEGAwAD8CwACQEEAKALwjdCAACIBRQ0AQQAhAgNAAkACQAJAIABBgMAARg0AIABBGGwiAyoC9M3YgAAiBCADKgKAztiAAEMAAAA/lCIFk0MAAIA9lPwAIgYgBCAFkkMAAIA9lPwAIgdKDQIgAyoC/M3YgAAiBCADKgKIztiAAEMAAAA/lCIFk0MAAIA9lPwAIgggBCAFkkMAAIA9lPwAIglMDQEDQCAGIAdODQMgBiAGIAdIaiIGIAdKDQMMAAsLQYDAAEGAwABBnILAgAAQg4CAgAAACwNAIAYiCkHdCGwhCyACQQJ0QfCJwIAAaiEMIAJBAXRB9q3QgABqIQ0gCiAKIAdIaiEGIAghAwNAIAJBAWoiAkH//wNLDQQgDSAAOwEAIANBnwFsIAtzQf8PcUECdCIOKAL0zeSAACEPIA4gAjYC9M3kgAAgDCAPNgIAAkAgAyAJTg0AIAxBBGohDCANQQJqIQ0gAyADIAlIaiIDIAlMDQELCyAKIAdODQEgBiAHTA0ACwsgAEEBaiIAIAFHDQALCwtfAgF/AX4jgICAgABBIGsiAySAgICAACADIAE2AgwgAyAANgIIIANBgYCAgACtQiCGIgQgA0EIaq2ENwMYIAMgBCADQQxqrYQ3AxBBgIDAgAAgA0EQaiACEKCAgIAAAAsLAEEAKgL0jeWAAAsLAEEAKgL4jeWAAAsIAEHsh8CAAAsIAEH8jeWAAAsIAEH8keWAAAsIAEH0wdiAAAsIAEH0xdiAAAsIAEH0rdiAAAsIAEH0sdiAAAsIAEH0tdiAAAspAQF/QQAhAQJAIABBACgC7I3QgABPDQAgAEECdCgC9I3QgAAhAQsgAQsLAEEAKALsjdCAAAsIAEHsiMCAAAsIAEH0ydiAAAsIAEHsidCAAAsIAEH8leWAAAsIAEH0udiAAAsIAEH0vdiAAAumAgQBfwF9An8CfQJAAkAgACABQ83MzD4Ql4CAgAAiBA0AQwDAecQhAwwBCyACIAOSIQVDAMB5xCEDQYBgIQYDQAJAAkACQCAGRQ0AIAZB9K3QgABqKAIAIgdBgMAATw0BIAdBGGwiByoC+M3YgAAgByoChM7YgABDAAAAP5SSIgIgBV9FDQIgAiADXkUNAiACIAMgACAHQfTN2IAAaiIHKgIMQwAAAD+UIgggByoCACIJkl8bIAMgACAJIAiTYBsgAyABIAcqAggiAiAHKgIUQwAAAD+UIgiTYBsgAyABIAggApJfGyEDDAILQYAIQYAIQayCwIAAEIOAgIAAAAsgB0GAwABBvILAgAAQg4CAgAAACyAGQQRqIQYgBEF/aiIEDQALCyADC/kDAQ9/QQAhA0EAQQA2AuyN0IAAAkAgACACk0MAAIA9lPwAIgQgACACkkMAAIA9lPwAIgVKDQACQAJAIAEgApNDAACAPZT8ACIGIAEgApJDAACAPZT8ACIHSg0AQQAhAwwBCwNAIAQgBU4NAiAEIAQgBUhqIgQgBUwNAAwCCwsDQCAEIghB3QhsIQkgCCAIIAVIaiEEIAYhCiADIQsDQAJAIApBnwFsIAlzQf8PcUECdCgC9M3kgAAiDEUNAANAAkACQAJAAkAgDEH//wNLDQAgDEEBdC8B9K3QgAAhDUEAIQ5B9I3QgAAhDyALIRADQCAQRQ0DIA5BgAhGDQIgDygCACANRg0EIA5BAXIgC0YNAyAPQQRqKAIAIA1GDQQgDkECciALRg0DIA9BCGooAgAgDUYNBCAOQQNyIAtGDQMgDkEEaiEOIBBBfGohECAPQQxqIREgD0EQaiEPIBEoAgAgDUcNAAwECwsgDEGAgARBzILAgAAQg4CAgAAAC0GACEGACEHcgsCAABCDgICAAAALIAtBgAhPDQBBACALQQFqIgM2AuyN0IAAIAtBAnQgDTYC9I3QgAAgAyELCyAMQQJ0KALsicCAACIMDQALCwJAIAogB04NACAKIAogB0hqIgogB0wNAQsLIAggBU4NASAEIAVMDQALCyADCycAQQBBADYC8I3QgABB9M3kgABBAEGAwAD8CwBBAEEANgLsjdCAAAukCQkBfQF/AX0DfwF9A38BfQF/Bn0gAiAClCEFQX8hBkMAAAAAIQdBACEIIAAgASACEJeAgIAAIQkDQCAGIQogByELA0AgCSAIIAkgCEsbIQwgCEGACCAIQYAISxshDSAIQQJ0QfSN0IAAaiEOAkACQAJAAkACQAJAAkADQAJAIAwgCEcNAEEAIQggACABIAIQl4CAgAAhDANAIAohCSALIQ8DQCAMIAggDCAISxshECAIQYAIIAhBgAhLGyENIAhBAnRB9I3QgABqIQ4DQCAQIAhGDQUgDSAIRg0GAkAgDigCACIKQf8/TQ0AIAohBgwMCyAIQQFqIQggDkEEaiEOIAQgCkEYbCIGKgL4zdiAACIHIAYqAoTO2IAAQwAAAD+UIhGTXw0AIAMgByARkmANAAsgBkH0zdiAAGoiDioCFEMAAAA/lCEHIA4qAgAiEiAOKgIMQwAAAD+UIguSIRMgDioCCCERIBIgC5MiFCESAkAgACAUXQ0AIAAhEiAAIBNeRQ0AIBMhEgsgESAHkiEVIBEgB5MiESEHAkAgASARXQ0AIAEhByABIBVeRQ0AIBUhBwsgACASkyISIBKUIAEgB5MiByAHlJIiCyAFXUUNAAJAAkAgC0O9N4Y1Xg0AIAEgEZOLIQsgEyAAk4shBwJAAkAgACAUk4siEiAVIAGTiyIWXUUNACASIAddRQ0AIBIgC10NAQsCQAJAIAcgC11FDQAgByAWXQ0BCwJAIAsgFl0NACACIBaSIQsgAiAVkiEBDAQLIAIgC5IhCyARIAKTIQEMAwsgAiAHkiELIAIgE5IhAAwCCyACIBKSIQsgFCACkyEADAELIAEgByACIAuRIhGTIgsgEZUiEZSSIQEgACASIBGUkiEACyALIA9eDQEMAAsLCyANIAhGDQIgDigCACIGQYDAAE8NByAIQQFqIQggDkEEaiEOIAQgBkEYbCIQKgL4zdiAACIHIBAqAoTO2IAAQwAAAD+UIhGTXw0AIAMgByARkmANAAsgEEH0zdiAAGoiDioCFEMAAAA/lCEHIA4qAgAiEiAOKgIMQwAAAD+UIhSSIRUgDioCCCERIBIgFJMiFCESAkAgACAUXQ0AIAAhEiAAIBVeRQ0AIBUhEgsgESAHkiEPIBEgB5MiESEHAkAgASARXQ0AIAEhByABIA9eRQ0AIA8hBwsgACASkyISIBKUIAEgB5MiEyATlJIiByAFXUUNByAHQ703hjVeDQIgASARk4shEyAVIACTiyEHAkAgACAUk4siEiAPIAGTiyIWXUUNACASIAddRQ0AIBIgE10NBAsCQCAHIBNdRQ0AIAcgFl0NBQsCQCATIBZdDQAgAiAWkiEHIAIgD5IhAQwGCyACIBOSIQcgESACkyEBDAULQQAgATgC+I3lgABBACAAOAL0jeWAACAJDwsgDUGACEHsgsCAABCDgICAAAALIAEgEyACIAeRIhGTIgcgEZUiEZSSIQEgACASIBGUkiEADAILIAIgEpIhByAUIAKTIQAMAQsgAiAHkiEHIAIgFZIhAAsgByALXg0CDAELCwsgBkGAwABB/ILAgAAQg4CAgAAAC1UAAkAgAEGAwABPDQAgAEEYbCIAIAY4AojO2IAAIAAgBTgChM7YgAAgACAEOAKAztiAACAAIAM4AvzN2IAAIAAgAjgC+M3YgAAgACABOAL0zdiAAAsLGQBBACAAQYDAACAAQYDAAEkbNgLwjdCAAAscAAJAIABFDQAgACABEJ2AgIAAAAsQnoCAgAAACw0AIAEgABCfgICAAAALFwBBjIPAgABBI0Ggg8CAABCggICAAAALDQAgASAAEMOAgIAAAAtHAQF/I4CAgIAAQSBrIgMkgICAgAAgAyABNgIQIAMgADYCDCADQQE7ARwgAyACNgIYIAMgA0EMajYCFCADQRRqEKKAgIAAAAvBCgEMfyAAKAIEIQIgACgCACEDAkACQCABKAIIIgRBgICAwAFxRQ0AAkACQCAEQYCAgIABcQ0AAkAgAkEQSQ0AIAIgAyADQQNqQXxxIgVrIgZqIgdBA3EhCEEAIQlBACEAAkAgAyAFRg0AQQAhCkEAIQACQCAGQXxLDQBBACEKQQAhAANAIAAgAyAKaiILLAAAQb9/SmogC0EBaiwAAEG/f0pqIAtBAmosAABBv39KaiALQQNqLAAAQb9/SmohACAKQQRqIgoNAAsLIAMgCmohCwNAIAAgCywAAEG/f0pqIQAgC0EBaiELIAZBAWoiBg0ACwsCQCAIRQ0AIAUgB0H8////B3FqIgssAABBv39KIQkgCEEBRg0AIAkgCywAAUG/f0pqIQkgCEECRg0AIAkgCywAAkG/f0pqIQkLIAdBAnYhCCAJIABqIQoDQCAFIQkgCEUNAyAIQcABIAhBwAFJGyIHQQNxIQwCQAJAIAdBAnQiDUHwB3EiAA0AQQAhCwwBCyAJIABqIQZBACELIAkhAANAIABBDGooAgAiBUF/c0EHdiAFQQZ2ckGBgoQIcSAAQQhqKAIAIgVBf3NBB3YgBUEGdnJBgYKECHEgAEEEaigCACIFQX9zQQd2IAVBBnZyQYGChAhxIAAoAgAiBUF/c0EHdiAFQQZ2ckGBgoQIcSALampqaiELIABBEGoiACAGRw0ACwsgCCAHayEIIAkgDWohBSALQQh2Qf+B/AdxIAtB/4H8B3FqQYGABGxBEHYgCmohCiAMRQ0ACyAJIAdB/AFxQQJ0aiILKAIAIgBBf3NBB3YgAEEGdnJBgYKECHEhAAJAIAxBAUYNACALKAIEIgVBf3NBB3YgBUEGdnJBgYKECHEgAGohACAMQQJGDQAgCygCCCILQX9zQQd2IAtBBnZyQYGChAhxIABqIQALIABBCHZB/4EccSAAQf+B/AdxakGBgARsQRB2IApqIQoMAgsCQCACDQBBACEKDAILIAJBA3EhC0EAIQVBACEKAkAgAkEESQ0AIAJBDHEhBkEAIQpBACEFA0AgCiADIAVqIgAsAABBv39KaiAAQQFqLAAAQb9/SmogAEECaiwAAEG/f0pqIABBA2osAABBv39KaiEKIAYgBUEEaiIFRw0ACyALRQ0CCyADIAVqIQADQCAKIAAsAABBv39KaiEKIABBAWohACALQX9qIgsNAAwCCwsCQAJAAkAgAS8BDiIKDQBBACECDAELIAMgAmohBkEAIQIgAyELIAohBQNAIAsiACAGRg0CAkACQCAALAAAIgtBf0wNACAAQQFqIQsMAQsCQCALQWBPDQAgAEECaiELDAELIABBBEEDIAtBb0sbaiELCyALIABrIAJqIQIgBUF/aiIFDQALC0EAIQULIAogBWshCgsgCiABLwEMIgBJDQELIAEoAgAgAyACIAEoAgQoAgwRgICAgACAgICAAA8LIAAgCmshCUEAIQBBACEIAkACQAJAIARBHXZBA3EOBAIAAQICCyAJIQgMAQsgCUH+/wNxQQF2IQgLIARB////AHEhCiABKAIEIQsgASgCACEFAkACQANAIABB//8DcSAIQf//A3FPDQFBASEGIABBAWohACAFIAogCygCEBGBgICAAICAgIAARQ0ADAILC0EBIQYgBSADIAIgCygCDBGAgICAAICAgIAADQAgCSAIa0H//wNxIQhBACEAA0ACQCAAQf//A3EgCEkNAEEADwtBASEGIABBAWohACAFIAogCygCEBGBgICAAICAgIAARQ0ACwsgBgs4AgF/AX4jgICAgABBEGsiASSAgICAACAAKQIAIQIgASAANgIMIAEgAjcCBCABQQRqEK6AgIAAAAv0BAEIfyOAgICAAEEQayIEJICAgIAAAkACQAJAIANBAXENACACLQAAIgUNAUEAIQUMAgsgACACIANBAXYgASgCDBGAgICAAICAgIAAIQUMAQsgASgCDCEGQQAhBwNAIAJBAWohCAJAAkACQAJAAkAgBcBBf0oNACAFQf8BcSIJQYABRg0BIAlBwAFHDQMgBCABNgIEIAQgADYCACAEQqCAgIAGNwIIIAMgB0EDdGoiBSgCACAEIAUoAgQRgYCAgACAgICAAEUNAkEBIQUMBgsCQCAAIAggBUH/AXEiBSAGEYCAgIAAgICAgAANACAIIAVqIQIMBAtBASEFDAULAkAgACACQQNqIgUgAi8AASICIAYRgICAgACAgICAAA0AIAUgAmohAgwDC0EBIQUMBAsgB0EBaiEHIAghAgwBC0GggICABiEKAkAgBUEBcUUNACACQQVqIQggAigAASEKC0EAIQkCQAJAIAVBAnENAEEAIQsgCCECDAELIAhBAmohAiAILwAAIQsLAkACQCAFQQRxDQAgAiEIDAELIAJBAmohCCACLwAAIQkLAkACQCAFQQhxDQAgCCECDAELIAhBAmohAiAILwAAIQcLAkAgBUEQcUUNACADIAtB//8DcUEDdGovAQQhCwsCQCAFQSBxRQ0AIAMgCUH//wNxQQN0ai8BBCEJCyAEIAk7AQ4gBCALOwEMIAQgCjYCCCAEIAE2AgQgBCAANgIAAkAgAyAHQQN0aiIFKAIAIAQgBSgCBBGBgICAAICAgIAARQ0AQQEhBQwDCyAHQQFqIQcLIAItAAAiBQ0AC0EAIQULIARBEGokgICAgAAgBQvfBgILfwF+I4CAgIAAQRBrIgIkgICAgABBCiEDIAAoAgAiBCEFAkAgBEHoB0kNAEEKIQMgBCEFA0AgAkEGaiADaiIGQXxqIAUiACAAQZDOAG4iBUGQzgBsayIHQf//A3FB5ABuIghBAXQvALCDwIAAOwAAIAZBfmogByAIQeQAbGtB//8DcUEBdC8AsIPAgAA7AAAgA0F8aiEDIABB/6ziBEsNAAsLAkACQCAFQQlLDQAgBSEADAELIAJBBmogA0F+aiIDaiAFIAVB//8DcUHkAG4iAEHkAGxrQf//A3FBAXQvALCDwIAAOwAACwJAAkAgBEUNACAARQ0BCyACQQZqIANBf2oiA2ogAEEBdC0AsYPAgAA6AAALQStBfyABKAIIIgBBgICAAXEiBRshBCAAQYCAgARxQRd2IQkgAkEGaiADaiEKAkACQCAFQRV2QQogA2siC2oiByABLwEMIghPDQACQAJAAkAgAEGAgIAIcQ0AIAggB2shDEEAIQNBACEIAkACQAJAIABBHXZBA3EOBAIAAQACCyAMIQgMAQsgDEH+/wNxQQF2IQgLIABB////AHEhByABKAIEIQYgASgCACEFA0AgA0H//wNxIAhB//8DcU8NAkEBIQAgA0EBaiEDIAUgByAGKAIQEYGAgIAAgICAgABFDQAMBQsLIAEgASkCCCINp0GAgID/eXFBsICAgAJyNgIIQQEhACABKAIAIgUgASgCBCIGIAQgCRClgICAAA0DQQAhAyAIIAdrQf//A3EhBwNAIANB//8DcSAHTw0CQQEhACADQQFqIQMgBUEwIAYoAhARgYCAgACAgICAAEUNAAwECwtBASEAIAUgBiAEIAkQpYCAgAANAiAFIAogCyAGKAIMEYCAgIAAgICAgAANAiAMIAhrQf//A3EhCEEAIQMDQAJAIANB//8DcSAISQ0AQQAhAAwEC0EBIQAgA0EBaiEDIAUgByAGKAIQEYGAgIAAgICAgABFDQAMAwsLQQEhACAFIAogCyAGKAIMEYCAgIAAgICAgAANASABIA03AghBACEADAELQQEhACABKAIAIgMgASgCBCIFIAQgCRClgICAAA0AIAMgCiALIAUoAgwRgICAgACAgICAACEACyACQRBqJICAgIAAIAALRgACQCACQX9GDQAgACACIAEoAhARgYCAgACAgICAAEUNAEEBDwsCQCADDQBBAA8LIAAgA0EAIAEoAgwRgICAgACAgICAAAsQACAAQd0AIAEQoICAgAAAC1IBAX8jgICAgABBEGsiACSAgICAACAAQRw2AgQgAEHohsCAADYCACAAQYKAgIAArUIghiAArYQ3AwhBtYDAgAAgAEEIakGEh8CAABCggICAAAAL6gEBAn8jgICAgABBEGsiBCSAgICAAEEAQQAoAoya5YAAIgVBAWo2Aoya5YAAAkACQAJAIAVBAEgNAAJAAkBBAC0AhJrlgAANAEEAQQE6AISa5YAAQQBBACgCgJrlgABBAWo2AoCa5YAAQQAoAoia5YAAIgVBf0wNAiAFQQFqIgEgBU4NARCngICAAAALIARBCGogACABKAIYEYKAgIAAgICAgAAAC0EAIAFBf2o2Aoia5YAAIAFBAEwNAUEAQQA6AISa5YAAIAINAgsAC0G0h8CAAEHNAEHch8CAABCggICAAAALEKmAgIAAAAsDAAALsioCCH8BfgJAAkACQCAAQfQBSw0AAkACQAJAAkBBACgCqJ3lgAAiAUEQIABBC2pB+ANxIABBC0kbIgJBA3YiA3YiAEEDcQ0AIAJBACgCsJ3lgABNDQUgAA0BQQAoAqyd5YAAIgBFDQUgAGhBAnRBkJrlgABqKAIAIgQoAgRBeHEgAmshAyAEIQEDQAJAIAQoAhAiAA0AIAQoAhQiAA0AIAEoAhghBQJAAkACQCABKAIMIgAgAUcNACABQRRBECABKAIUIgAbaigCACIEDQFBACEADAILIAEoAggiBCAANgIMIAAgBDYCCAwBCyABQRRqIAFBEGogABshBgNAIAYhByAEIgBBFGogAEEQaiAAKAIUIgQbIQYgAEEUQRAgBBtqKAIAIgQNAAsgB0EANgIACyAFRQ0FAkACQCABIAEoAhxBAnRBkJrlgABqIgQoAgBGDQACQCAFKAIQIAFGDQAgBSAANgIUIAANAgwICyAFIAA2AhAgAA0BDAcLIAQgADYCACAARQ0FCyAAIAU2AhgCQCABKAIQIgRFDQAgACAENgIQIAQgADYCGAsgASgCFCIERQ0FIAAgBDYCFCAEIAA2AhgMBQsgACgCBEF4cSACayIEIAMgBCADSSIEGyEDIAAgASAEGyEBIAAhBAwACwsCQAJAIABBf3NBAXEgA2oiBkEDdCIAQaCb5YAAaiICIABBqJvlgABqKAIAIgMoAggiBEYNACAEIAI2AgwgAiAENgIIDAELQQAgAUF+IAZ3cTYCqJ3lgAALIAMgAEEDcjYCBCADIABqIgAgACgCBEEBcjYCBCADQQhqDwsCQAJAIAAgA3RBAiADdCIAQQAgAGtycWgiB0EDdCIDQaCb5YAAaiIEIANBqJvlgABqKAIAIgAoAggiBkYNACAGIAQ2AgwgBCAGNgIIDAELQQAgAUF+IAd3cTYCqJ3lgAALIAAgAkEDcjYCBCAAIAJqIgEgAyACayICQQFyNgIEIAAgA2ogAjYCAAJAQQAoArCd5YAAIgRFDQBBACgCuJ3lgAAhAwJAAkBBACgCqJ3lgAAiBkEBIARBA3Z0IgdxDQBBACAGIAdyNgKoneWAACAEQXhxQaCb5YAAaiIEIQYMAQsgBEF4cSIEQaCb5YAAaiEGIARBqJvlgABqKAIAIQQLIAYgAzYCCCAEIAM2AgwgAyAGNgIMIAMgBDYCCAtBACABNgK4neWAAEEAIAI2ArCd5YAAIABBCGoPC0EAQQAoAqyd5YAAQX4gASgCHHdxNgKsneWAAAsCQAJAAkAgA0EQSQ0AIAEgAkEDcjYCBCABIAJqIgQgA0EBcjYCBCAEIANqIAM2AgBBACgCsJ3lgAAiBkUNAUEAKAK4neWAACEAAkACQEEAKAKoneWAACIHQQEgBkEDdnQiBXENAEEAIAcgBXI2Aqid5YAAIAZBeHFBoJvlgABqIgYhBwwBCyAGQXhxIgZBoJvlgABqIQcgBkGom+WAAGooAgAhBgsgByAANgIIIAYgADYCDCAAIAc2AgwgACAGNgIIDAELIAEgAyACaiIAQQNyNgIEIAEgAGoiACAAKAIEQQFyNgIEDAELQQAgBDYCuJ3lgABBACADNgKwneWAAAsgAUEIaiIARQ0BDAILIABBC2oiA0F4cSECQQAoAqyd5YAAIghFDQBBHyEFAkAgAEH1//8HTw0AIAJBJiADQQh2ZyIAa3ZBAXEgAEEBdGtBPmohBQtBACACayEDAkACQAJAAkAgBUECdEGQmuWAAGooAgAiAQ0AQQAhBEEAIQAMAQtBACEEIAJBAEEZIAVBAXZrIAVBH0YbdCEGQQAhAANAAkAgASIBKAIEQXhxIgcgAkkNACAHIAJrIgcgA08NACABIQQgByEDIAcNAEEAIQMgASEAIAEhBAwDCyABKAIUIgcgACAHIAEgBkEddkEEcWooAhAiAUcbIAAgBxshACAGQQF0IQYgAQ0ACwsCQCAAIARyDQBBACEEQQIgBXQiAEEAIABrciAIcSIARQ0DIABoQQJ0QZCa5YAAaigCACEACyAARQ0BCwNAIAAoAgRBeHEiASACayIGIAMgBiADSSIHGyEFIAEgAkkhBiAAIAQgBxshBwJAIAAoAhAiAQ0AIAAoAhQhAQsgAyAFIAYbIQMgBCAHIAYbIQQgASEAIAENAAsLIARFDQACQEEAKAKwneWAACIAIAJJDQAgAyAAIAJrTw0BCyAEKAIYIQUCQAJAAkAgBCgCDCIAIARHDQAgBEEUQRAgBCgCFCIAG2ooAgAiAQ0BQQAhAAwCCyAEKAIIIgEgADYCDCAAIAE2AggMAQsgBEEUaiAEQRBqIAAbIQYDQCAGIQcgASIAQRRqIABBEGogACgCFCIBGyEGIABBFEEQIAEbaigCACIBDQALIAdBADYCAAsCQCAFRQ0AAkACQAJAIAQgBCgCHEECdEGQmuWAAGoiASgCAEYNAAJAIAUoAhAgBEYNACAFIAA2AhQgAA0CDAQLIAUgADYCECAADQEMAwsgASAANgIAIABFDQELIAAgBTYCGAJAIAQoAhAiAUUNACAAIAE2AhAgASAANgIYCyAEKAIUIgFFDQEgACABNgIUIAEgADYCGAwBC0EAQQAoAqyd5YAAQX4gBCgCHHdxNgKsneWAAAsCQAJAAkACQCADQRBJDQAgBCACQQNyNgIEIAQgAmoiASADQQFyNgIEIAEgA2ogAzYCAAJAIANBgAJJDQBBHyEAIANBgICACEkNAgwDCwJAAkBBACgCqJ3lgAAiAEEBIANBA3Z0IgZxDQBBACAAIAZyNgKoneWAACADQfgBcUGgm+WAAGoiACEDDAELIANB+AFxIgBBoJvlgABqIQMgAEGom+WAAGooAgAhAAsgAyABNgIIIAAgATYCDCABIAM2AgwgASAANgIIDAMLIAQgAyACaiIAQQNyNgIEIAQgAGoiACAAKAIEQQFyNgIEDAILIANBJiADQQh2ZyIAa3ZBAXEgAEEBdHJBPnMhAAsgAUIANwIQIAEgADYCHCAAQQJ0QZCa5YAAaiEGAkBBACgCrJ3lgABBASAAdCIHcQ0AIAYgATYCACABIAY2AhggASABNgIMIAEgATYCCEEAQQAoAqyd5YAAIAdyNgKsneWAAAwBCwJAAkACQCAGKAIAIgcoAgRBeHEgA0cNACAHIQAMAQsgA0EAQRkgAEEBdmsgAEEfRht0IQYDQCAHIAZBHXZBBHFqIgUoAhAiAEUNAiAGQQF0IQYgACEHIAAoAgRBeHEgA0cNAAsLIAAoAggiAyABNgIMIAAgATYCCCABQQA2AhggASAANgIMIAEgAzYCCAwBCyAFQRBqIAE2AgAgASAHNgIYIAEgATYCDCABIAE2AggLIARBCGoiAA0BCwJAAkACQAJAAkACQEEAKAKwneWAACIAIAJPDQACQEEAKAK0neWAACIAIAJLDQBBACEAQQAtAPyZ5YAAIQRBAEEBOgD8meWAAEHgneWAACEBIAJBr4AEaiIGQYCAfHEhAwJAAkBBgIDogABB4J3lgABNDQAgA0GAgOiAAEHgneWAAGtLDQAgBEH/AXENAEGAgOiAAEHgneWAAGshBwwBCyAGQRB2QAAiBEF/Rg0IQQAhACAEQRB0IgFFDQggA0FwaiADIAFBACADa0YbIQcLQQBBACgCwJ3lgAAgB2oiADYCwJ3lgABBACAAQQAoAsSd5YAAIgMgACADSxs2AsSd5YAAAkACQAJAQQAoAryd5YAAIgNFDQBBkJvlgAAhAANAIAEgACgCACIEIAAoAgQiBmpGDQIgACgCCCIADQAMAwsLAkACQEEAKALMneWAACIARQ0AIAEgAE8NAQtBACABNgLMneWAAAtBAEH/HzYC0J3lgABBACAHNgKUm+WAAEEAIAE2ApCb5YAAQQBBoJvlgAA2Aqyb5YAAQQBBqJvlgAA2ArSb5YAAQQBBoJvlgAA2Aqib5YAAQQBBsJvlgAA2Aryb5YAAQQBBqJvlgAA2ArCb5YAAQQBBuJvlgAA2AsSb5YAAQQBBsJvlgAA2Arib5YAAQQBBwJvlgAA2Asyb5YAAQQBBuJvlgAA2AsCb5YAAQQBByJvlgAA2AtSb5YAAQQBBwJvlgAA2Asib5YAAQQBB0JvlgAA2Atyb5YAAQQBByJvlgAA2AtCb5YAAQQBB2JvlgAA2AuSb5YAAQQBB0JvlgAA2Atib5YAAQQBBADYCnJvlgABBAEHgm+WAADYC7JvlgABBAEHYm+WAADYC4JvlgABBAEHgm+WAADYC6JvlgABBAEHom+WAADYC9JvlgABBAEHom+WAADYC8JvlgABBAEHwm+WAADYC/JvlgABBAEHwm+WAADYC+JvlgABBAEH4m+WAADYChJzlgABBAEH4m+WAADYCgJzlgABBAEGAnOWAADYCjJzlgABBAEGAnOWAADYCiJzlgABBAEGInOWAADYClJzlgABBAEGInOWAADYCkJzlgABBAEGQnOWAADYCnJzlgABBAEGQnOWAADYCmJzlgABBAEGYnOWAADYCpJzlgABBAEGYnOWAADYCoJzlgABBAEGgnOWAADYCrJzlgABBAEGonOWAADYCtJzlgABBAEGgnOWAADYCqJzlgABBAEGwnOWAADYCvJzlgABBAEGonOWAADYCsJzlgABBAEG4nOWAADYCxJzlgABBAEGwnOWAADYCuJzlgABBAEHAnOWAADYCzJzlgABBAEG4nOWAADYCwJzlgABBAEHInOWAADYC1JzlgABBAEHAnOWAADYCyJzlgABBAEHQnOWAADYC3JzlgABBAEHInOWAADYC0JzlgABBAEHYnOWAADYC5JzlgABBAEHQnOWAADYC2JzlgABBAEHgnOWAADYC7JzlgABBAEHYnOWAADYC4JzlgABBAEHonOWAADYC9JzlgABBAEHgnOWAADYC6JzlgABBAEHwnOWAADYC/JzlgABBAEHonOWAADYC8JzlgABBAEH4nOWAADYChJ3lgABBAEHwnOWAADYC+JzlgABBAEGAneWAADYCjJ3lgABBAEH4nOWAADYCgJ3lgABBAEGIneWAADYClJ3lgABBAEGAneWAADYCiJ3lgABBAEGQneWAADYCnJ3lgABBAEGIneWAADYCkJ3lgABBAEGYneWAADYCpJ3lgABBAEGQneWAADYCmJ3lgABBACABQQ9qQXhxIgBBeGoiAzYCvJ3lgABBAEGYneWAADYCoJ3lgABBACABIABrIAdBWGoiAGpBCGoiBDYCtJ3lgAAgAyAEQQFyNgIEIAEgAGpBKDYCBEEAQYCAgAE2Asid5YAADAgLIAMgAU8NACAEIANLDQAgACgCDEUNAwtBAEEAKALMneWAACIAIAEgACABSRs2Asyd5YAAIAEgB2ohBEGQm+WAACEAAkACQAJAA0AgACgCACIGIARGDQEgACgCCCIADQAMAgsLIAAoAgxFDQELQZCb5YAAIQACQANAAkAgACgCACIEIANLDQAgAyAEIAAoAgRqIgRJDQILIAAoAgghAAwACwtBACABQQ9qQXhxIgBBeGoiBjYCvJ3lgABBACABIABrIAdBWGoiAGpBCGoiBTYCtJ3lgAAgBiAFQQFyNgIEIAEgAGpBKDYCBEEAQYCAgAE2Asid5YAAIAMgBEFgakF4cUF4aiIAIAAgA0EQakkbIgZBGzYCBEEAKQKQm+WAACEJIAZBEGpBACkCmJvlgAA3AgAgBkEIaiIAIAk3AgBBACAHNgKUm+WAAEEAIAE2ApCb5YAAQQAgADYCmJvlgABBAEEANgKcm+WAACAGQRxqIQADQCAAQQc2AgAgAEEEaiIAIARJDQALIAYgA0YNByAGIAYoAgRBfnE2AgQgAyAGIANrIgBBAXI2AgQgBiAANgIAAkAgAEGAAkkNACADIAAQwoCAgAAMCAsCQAJAQQAoAqid5YAAIgRBASAAQQN2dCIBcQ0AQQAgBCABcjYCqJ3lgAAgAEH4AXFBoJvlgABqIgAhBAwBCyAAQfgBcSIAQaCb5YAAaiEEIABBqJvlgABqKAIAIQALIAQgAzYCCCAAIAM2AgwgAyAENgIMIAMgADYCCAwHCyAAIAE2AgAgACAAKAIEIAdqNgIEIAFBD2pBeHFBeGoiASACQQNyNgIEIAZBD2pBeHFBeGoiBCABIAJqIgBrIQMgBEEAKAK8neWAAEYNAyAEQQAoArid5YAARg0EAkAgBCgCBCICQQNxQQFHDQAgBCACQXhxIgIQvICAgAAgAiADaiEDIAQgAmoiBCgCBCECCyAEIAJBfnE2AgQgACADQQFyNgIEIAAgA2ogAzYCAAJAIANBgAJJDQAgACADEMKAgIAADAYLAkACQEEAKAKoneWAACICQQEgA0EDdnQiBHENAEEAIAIgBHI2Aqid5YAAIANB+AFxQaCb5YAAaiIDIQIMAQsgA0H4AXEiA0Ggm+WAAGohAiADQaib5YAAaigCACEDCyACIAA2AgggAyAANgIMIAAgAjYCDCAAIAM2AggMBQtBACAAIAJrIgM2ArSd5YAAQQBBACgCvJ3lgAAiACACaiIENgK8neWAACAEIANBAXI2AgQgACACQQNyNgIEIABBCGohAAwGC0EAKAK4neWAACEDAkACQCAAIAJrIgRBD0sNAEEAQQA2Arid5YAAQQBBADYCsJ3lgAAgAyAAQQNyNgIEIAMgAGoiACAAKAIEQQFyNgIEDAELQQAgBDYCsJ3lgABBACADIAJqIgE2Arid5YAAIAEgBEEBcjYCBCADIABqIAQ2AgAgAyACQQNyNgIECyADQQhqDwsgACAGIAdqNgIEQQBBACgCvJ3lgAAiAEEPakF4cSIDQXhqIgQ2Aryd5YAAQQAgACADa0EAKAK0neWAACAHaiIDakEIaiIBNgK0neWAACAEIAFBAXI2AgQgACADakEoNgIEQQBBgICAATYCyJ3lgAAMAwtBACAANgK8neWAAEEAQQAoArSd5YAAIANqIgM2ArSd5YAAIAAgA0EBcjYCBAwBC0EAIAA2Arid5YAAQQBBACgCsJ3lgAAgA2oiAzYCsJ3lgAAgACADQQFyNgIEIAAgA2ogAzYCAAsgAUEIag8LQQAhAEEAKAK0neWAACIDIAJNDQBBACADIAJrIgM2ArSd5YAAQQBBACgCvJ3lgAAiACACaiIENgK8neWAACAEIANBAXI2AgQgACACQQNyNgIEIABBCGoPCyAACwkAIABBADYCAAseACAAQQApAtCFwIAANwIIIABBACkCyIXAgAA3AgALDgBBAEEBOgDUneWAAAALCwAgABCvgICAAAALjAEBA38jgICAgABBEGsiASSAgICAAAJAIAAoAgAiAigCBCIDQQFxRQ0AIAIoAgAhAiABIANBAXY2AgQgASACNgIAIAFBkIXAgAAgACgCCCIALQAIIAAtAAkQqICAgAAACyABQX82AgAgASAANgIMIAFBrIXAgAAgACgCCCIALQAIIAAtAAkQqICAgAAAC4ABAQN/AkACQAJAIAAoAgAiAUEBSA0AIAAoAgQiAkF8aigCACIAQXhxIgNBBEEIIABBA3EiABsgAWpJDQECQCAARQ0AIAMgAUEnaksNAwsgAhCxgICAAAsPC0HohcCAAEGYhsCAABCmgICAAAALQaiGwIAAQdiGwIAAEKaAgIAAAAupCQEFfyAAQXhqIgEgAEF8aigCACICQXhxIgBqIQMCQAJAIAJBAXENACACQQJxRQ0BIAEoAgAiAiAAaiEAAkAgASACayIBQQAoArid5YAARw0AIAMoAgRBA3FBA0cNAUEAIAA2ArCd5YAAIAMgAygCBEF+cTYCBCABIABBAXI2AgQgAyAANgIADwsgASACELyAgIAACwJAAkACQAJAAkACQAJAAkAgAygCBCICQQJxDQAgA0EAKAK8neWAAEYNAiADQQAoArid5YAARg0DIAMgAkF4cSICELyAgIAAIAEgAiAAaiIAQQFyNgIEIAEgAGogADYCACABQQAoArid5YAARw0BQQAgADYCsJ3lgAAPCyADIAJBfnE2AgQgASAAQQFyNgIEIAEgAGogADYCAAsgAEGAAkkNAkEfIQMgAEGAgIAISQ0DDAULQQAgATYCvJ3lgABBAEEAKAK0neWAACAAaiIANgK0neWAACABIABBAXI2AgQCQCABQQAoArid5YAARw0AQQBBADYCsJ3lgABBAEEANgK4neWAAAsgAEEAKALIneWAACICTQ0FQQAoAryd5YAAIgBFDQVBACgCtJ3lgAAiBEEpSQ0DQZCb5YAAIQEDQAJAIAEoAgAiAyAASw0AIAAgAyABKAIEakkNBQsgASgCCCEBDAALC0EAIAE2Arid5YAAQQBBACgCsJ3lgAAgAGoiADYCsJ3lgAAgASAAQQFyNgIEIAEgAGogADYCAA8LAkACQEEAKAKoneWAACIDQQEgAEEDdnQiAnENAEEAIAMgAnI2Aqid5YAAIABB+AFxQaCb5YAAaiIAIQMMAQsgAEH4AXEiAEGgm+WAAGohAyAAQaib5YAAaigCACEACyADIAE2AgggACABNgIMIAEgAzYCDCABIAA2AggPCyAAQSYgAEEIdmciA2t2QQFxIANBAXRyQT5zIQMMAQsCQAJAQQAoApib5YAAIgANAEH/HyEBDAELQQAhAQNAIAFBAWohASAAKAIIIgANAAsgAUH/HyABQf8fSxshAQtBACABNgLQneWAACAEIAJNDQFBAEF/NgLIneWAAAwBCyABQgA3AhAgASADNgIcIANBAnRBkJrlgABqIQICQAJAQQAoAqyd5YAAQQEgA3QiBHENACACIAE2AgAgASACNgIYIAEgATYCDCABIAE2AghBAEEAKAKsneWAACAEcjYCrJ3lgAAMAQsCQAJAAkAgAigCACIEKAIEQXhxIABHDQAgBCEDDAELIABBAEEZIANBAXZrIANBH0YbdCECA0AgBCACQR12QQRxaiIFKAIQIgNFDQIgAkEBdCECIAMhBCADKAIEQXhxIABHDQALCyADKAIIIgAgATYCDCADIAE2AgggAUEANgIYIAEgAzYCDCABIAA2AggMAQsgBUEQaiABNgIAIAEgBDYCGCABIAE2AgwgASABNgIIC0EAQQAoAtCd5YAAQX9qIgE2AtCd5YAAIAENAAJAAkBBACgCmJvlgAAiAA0AQf8fIQEMAQtBACEBA0AgAUEBaiEBIAAoAggiAA0ACyABQf8fIAFB/x9LGyEBC0EAIAE2AtCd5YAADwsLVAACQCAAKAIAQX9GDQAgASgCACAAKAIEIAAoAgggASgCBCgCDBGAgICAAICAgIAADwsgASgCACABKAIEIAAoAgwoAgAiACgCACAAKAIEEKOAgIAAC/0BAgJ/AX4jgICAgABBIGsiAiSAgICAAAJAIAEoAgBBf0cNACABKAIMIQMgAkEANgIYIAJCgICAgBA3AhAgAkEQakH4hMCAACADKAIAIgMoAgAgAygCBBCjgICAABogAiACKAIYIgM2AgggAiACKQIQIgQ3AwAgASADNgIIIAEgBDcCAAsgASgCCCEDIAFBADYCCCABKQIAIQQgAUKAgICAEDcCACACIAM2AhggAiAENwMQAkBBDBCqgICAACIBDQBBBEEMEJ2AgIAAAAsgASACKAIYNgIIIAEgAikDEDcCACAAQaSHwIAANgIEIAAgATYCACACQSBqJICAgIAAC6EBAgJ/AX4jgICAgABBIGsiAiSAgICAAAJAIAEoAgBBf0cNACABKAIMIQMgAkEANgIcIAJCgICAgBA3AhQgAkEUakH4hMCAACADKAIAIgMoAgAgAygCBBCjgICAABogAiACKAIcIgM2AhAgAiACKQIUIgQ3AwggASADNgIIIAEgBDcCAAsgAEGkh8CAADYCBCAAIAE2AgAgAkEgaiSAgICAAAufAQEBfyOAgICAAEEQayIDJICAgIAAAkAgAiABaiIBIAJPDQBBAEEAEJyAgIAAAAsgA0EEaiAAKAIAIgIgACgCBCABIAJBAXQiAiABIAJLGyICQQggAkEISxsiAhC2gICAAAJAIAMoAgRBAUcNACADKAIIIAMoAgwQnICAgAAACyADKAIIIQEgACACNgIAIAAgATYCBCADQRBqJICAgIAAC/AGAQV/AkACQCADQQBODQBBASEBQQQhAkEAIQMMAQsCQAJAAkACQAJAAkACQAJAAkAgAUUNACACQXxqIgQoAgAiBUF4cSIGQQRBCCAFQQNxIgcbIAFqSQ0BAkAgB0UNACAGIAFBJ2pLDQMLQRAgA0ELakF4cSADQQtJGyEBIAJBeGohCAJAIAcNACABQYACSQ0GIAhFDQYgBiABTQ0GIAYgAWtBgIAISw0GIAIhAQwHCyAIIAZqIQcCQAJAIAYgAU8NACAHQQAoAryd5YAARg0BAkAgB0EAKAK4neWAAEYNACAHKAIEIgVBAnENCCAFQXhxIgUgBmoiBiABSQ0IIAcgBRC8gICAAAJAIAYgAWsiB0EQSQ0AIAQgASAEKAIAQQFxckECcjYCACAIIAFqIgEgB0EDcjYCBCAIIAZqIgYgBigCBEEBcjYCBCABIAcQvYCAgAAMCAsgBCAGIAQoAgBBAXFyQQJyNgIAIAggBmoiASABKAIEQQFyNgIEDAcLQQAoArCd5YAAIAZqIgYgAUkNBwJAAkAgBiABayIHQQ9LDQAgBCAFQQFxIAZyQQJyNgIAIAggBmoiASABKAIEQQFyNgIEQQAhB0EAIQEMAQsgBCABIAVBAXFyQQJyNgIAIAggAWoiASAHQQFyNgIEIAggBmoiBiAHNgIAIAYgBigCBEF+cTYCBAtBACABNgK4neWAAEEAIAc2ArCd5YAADAYLIAYgAWsiBkEPTQ0FIAQgASAFQQFxckECcjYCACAIIAFqIgEgBkEDcjYCBCAHIAcoAgRBAXI2AgQgASAGEL2AgIAADAULQQAoArSd5YAAIAZqIgYgAUsNAwwFCyADEKqAgIAAIgENBQwGC0HohcCAAEGYhsCAABCmgICAAAALQaiGwIAAQdiGwIAAEKaAgIAAAAsgBCABIAVBAXFyQQJyNgIAIAggAWoiByAGIAFrIgFBAXI2AgRBACABNgK0neWAAEEAIAc2Aryd5YAACyAIRQ0AIAIhAQwBCyADEKqAgIAAIgFFDQECQCADQXxBeCAEKAIAIgZBA3EbIAZBeHFqIgYgAyAGSRsiBkUNACABIAIgBvwKAAALIAIQsYCAgAALIAAgATYCBEEAIQEMAQtBASEBIABBATYCBAtBCCECCyAAIAJqIAM2AgAgACABNgIAC34BA38CQAJAAkAgACgCACIBRQ0AIAAoAgQiAkF8aigCACIAQXhxIgNBBEEIIABBA3EiABsgAWpJDQECQCAARQ0AIAMgAUEnaksNAwsgAhCxgICAAAsPC0HohcCAAEGYhsCAABCmgICAAAALQaiGwIAAQdiGwIAAEKaAgIAAAAseACAAQQApAuCFwIAANwIIIABBACkC2IXAgAA3AgALWgEBfwJAAkACQCACIAAoAgAgACgCCCIDa00NACAAIAMgAhC1gICAACAAKAIIIQMMAQsgAkUNAQsgAkUNACAAKAIEIANqIAEgAvwKAAALIAAgAyACajYCCEEAC5oCAQZ/IAAoAgghAgJAAkAgAUGAAU8NAEEBIQMMAQsCQCABQYAQTw0AQQIhAwwBC0EDQQQgAUGAgARJGyEDCwJAIAMgACgCACACa00NACAAIAIgAxC1gICAAAsgACgCBCACaiEEAkACQCABQYABSQ0AIAFBP3FBgH9yIQUgAUEGdiEGAkAgAUGAEE8NACAEIAU6AAEgBCAGQcABcjoAAAwCCyABQQx2IQcgBkE/cUGAf3IhBgJAIAFB//8DSw0AIAQgBToAAiAEIAY6AAEgBCAHQeABcjoAAAwCCyAEIAU6AAMgBCAGOgACIAQgB0E/cUGAf3I6AAEgBCABQRJ2QXByOgAADAELIAQgAToAAAsgACADIAJqNgIIQQALFAAgAEH4hMCAACABIAIQo4CAgAALkgMBBH8gACgCDCECAkACQAJAAkAgAUGAAkkNACAAKAIYIQMCQAJAAkAgAiAARw0AIABBFEEQIAAoAhQiAhtqKAIAIgENAUEAIQIMAgsgACgCCCIBIAI2AgwgAiABNgIIDAELIABBFGogAEEQaiACGyEEA0AgBCEFIAEiAkEUaiACQRBqIAIoAhQiARshBCACQRRBECABG2ooAgAiAQ0ACyAFQQA2AgALIANFDQICQAJAIAAgACgCHEECdEGQmuWAAGoiASgCAEYNACADKAIQIABGDQEgAyACNgIUIAINAwwECyABIAI2AgAgAkUNBAwCCyADIAI2AhAgAg0BDAILAkAgAiAAKAIIIgRGDQAgBCACNgIMIAIgBDYCCA8LQQBBACgCqJ3lgABBfiABQQN2d3E2Aqid5YAADwsgAiADNgIYAkAgACgCECIBRQ0AIAIgATYCECABIAI2AhgLIAAoAhQiAUUNACACIAE2AhQgASACNgIYDwsPC0EAQQAoAqyd5YAAQX4gACgCHHdxNgKsneWAAAvuBgEEfyAAIAFqIQICQAJAAkACQAJAIAAoAgQiA0EBcQ0AIANBAnFFDQEgACgCACIDIAFqIQECQCAAIANrIgBBACgCuJ3lgABHDQAgAigCBEEDcUEDRw0BQQAgATYCsJ3lgAAgAiACKAIEQX5xNgIEIAAgAUEBcjYCBCACIAE2AgAPCyAAIAMQvICAgAALAkACQAJAIAIoAgQiA0ECcQ0AIAJBACgCvJ3lgABGDQIgAkEAKAK4neWAAEYNBCACIANBeHEiAxC8gICAACAAIAMgAWoiAUEBcjYCBCAAIAFqIAE2AgAgAEEAKAK4neWAAEcNAUEAIAE2ArCd5YAADwsgAiADQX5xNgIEIAAgAUEBcjYCBCAAIAFqIAE2AgALAkAgAUGAAkkNAEEfIQIgAUGAgIAISQ0EDAULAkACQEEAKAKoneWAACICQQEgAUEDdnQiA3ENAEEAIAIgA3I2Aqid5YAAIAFB+AFxQaCb5YAAaiIBIQIMAQsgAUH4AXEiAUGgm+WAAGohAiABQaib5YAAaigCACEBCyACIAA2AgggASAANgIMIAAgAjYCDCAAIAE2AggPC0EAIAA2Aryd5YAAQQBBACgCtJ3lgAAgAWoiATYCtJ3lgAAgACABQQFyNgIEIABBACgCuJ3lgABHDQBBAEEANgKwneWAAEEAQQA2Arid5YAACw8LQQAgADYCuJ3lgABBAEEAKAKwneWAACABaiIBNgKwneWAACAAIAFBAXI2AgQgACABaiABNgIADwsgAUEmIAFBCHZnIgJrdkEBcSACQQF0ckE+cyECCyAAQgA3AhAgACACNgIcIAJBAnRBkJrlgABqIQMCQEEAKAKsneWAAEEBIAJ0IgRxDQAgAyAANgIAIAAgAzYCGCAAIAA2AgwgACAANgIIQQBBACgCrJ3lgAAgBHI2Aqyd5YAADwsCQAJAAkAgAygCACIEKAIEQXhxIAFHDQAgBCECDAELIAFBAEEZIAJBAXZrIAJBH0YbdCEDA0AgBCADQR12QQRxaiIFKAIQIgJFDQIgA0EBdCEDIAIhBCACKAIEQXhxIAFHDQALCyACKAIIIgEgADYCDCACIAA2AgggAEEANgIYIAAgAjYCDCAAIAE2AggPCyAFQRBqIAA2AgAgACAENgIYIAAgADYCDCAAIAA2AggLJAAgASgCACAAKAIAIAAoAgQgASgCBCgCDBGAgICAAICAgIAAC0wBAn8gASgCBCECIAEoAgAhAwJAQQgQqoCAgAAiAQ0AQQRBCBCdgICAAAALIAEgAjYCBCABIAM2AgAgAEGUh8CAADYCBCAAIAE2AgALFAAgAEGUh8CAADYCBCAAIAE2AgALDAAgACABKQIANwMAC8MCAQR/QR8hAgJAIAFBgICACE8NACABQSYgAUEIdmciAmt2QQFxIAJBAXRyQT5zIQILIABCADcCECAAIAI2AhwgAkECdEGQmuWAAGohAwJAQQAoAqyd5YAAQQEgAnQiBHENACADIAA2AgAgACADNgIYIAAgADYCDCAAIAA2AghBAEEAKAKsneWAACAEcjYCrJ3lgAAPCwJAAkACQCADKAIAIgQoAgRBeHEgAUcNACAEIQIMAQsgAUEAQRkgAkEBdmsgAkEfRht0IQMDQCAEIANBHXZBBHFqIgUoAhAiAkUNAiADQQF0IQMgAiEEIAIoAgRBeHEgAUcNAAsLIAIoAggiAyAANgIMIAIgADYCCCAAQQA2AhggACACNgIMIAAgAzYCCA8LIAVBEGogADYCACAAIAQ2AhggACAANgIMIAAgADYCCAsNACAAIAEQrYCAgAAACwv2BwEAQYCAwAAL7AcgaW5kZXggb3V0IG9mIGJvdW5kczogdGhlIGxlbiBpcyDAEiBidXQgdGhlIGluZGV4IGlzIMAAL3J1c3RjLzJkODE0NGI3ODgwNTk3YjZlNmQzZGZkNjNhOWE5ZWZhZTNmNTMzZDMvbGlicmFyeS9zdGQvc3JjL3N5cy9zeW5jL3J3bG9jay9ub190aHJlYWRzLnJzAC9ydXN0Yy8yZDgxNDRiNzg4MDU5N2I2ZTZkM2RmZDYzYTlhOWVmYWUzZjUzM2QzL2xpYnJhcnkvYWxsb2Mvc3JjL3Jhd192ZWMvbW9kLnJzAC9ydXN0L2RlcHMvZGxtYWxsb2MtMC4yLjEzL3NyYy9kbG1hbGxvYy5ycwBzcmNcbGliLnJzABEBEAAKAAAAZgAAABUAAAARARAACgAAAAkBAAAWAAAAEQEQAAoAAAAKAQAAFQAAABEBEAAKAAAAjAAAACIAAAARARAACgAAAJAAAAAcAAAAEQEQAAoAAADCAAAAGgAAABEBEAAKAAAAwwAAABkAAABjYXBhY2l0eSBvdmVyZmxvdwAAAJUAEABQAAAAHAAAAAUAAAAwMDAxMDIwMzA0MDUwNjA3MDgwOTEwMTExMjEzMTQxNTE2MTcxODE5MjAyMTIyMjMyNDI1MjYyNzI4MjkzMDMxMzIzMzM0MzUzNjM3MzgzOTQwNDE0MjQzNDQ0NTQ2NDc0ODQ5NTA1MTUyNTM1NDU1NTY1NzU4NTk2MDYxNjI2MzY0NjU2NjY3Njg2OTcwNzE3MjczNzQ3NTc2Nzc3ODc5ODA4MTgyODM4NDg1ODY4Nzg4ODk5MDkxOTI5Mzk0OTU5Njk3OTg5OQMAAAAMAAAABAAAAAQAAAAFAAAABgAAAAAAAAAIAAAABAAAAAcAAAAIAAAACQAAAAoAAAALAAAAEAAAAAQAAAAMAAAADQAAAA4AAAAPAAAAXPbpX9wC9rnxwXBs8mHBJEr+DDRxT/df3zjkeSX+HHRhc3NlcnRpb24gZmFpbGVkOiBwc2l6ZSA+PSBzaXplICsgbWluX292ZXJoZWFkAADmABAAKgAAALEEAAAJAAAAYXNzZXJ0aW9uIGZhaWxlZDogcHNpemUgPD0gc2l6ZSArIG1heF9vdmVyaGVhZAAA5gAQACoAAAC3BAAADQAAAHJ3bG9jayBvdmVyZmxvd2VkIHJlYWQgbG9ja3M3ABAAXQAAABUAAAAsAAAAAAAAAAgAAAAEAAAAEAAAAAMAAAAMAAAABAAAABEAAAByd2xvY2sgaGFzIG5vdCBiZWVuIGxvY2tlZCBmb3IgcmVhZGluZwAANwAQAF0AAAA+AAAACQAAAA==';

    class BrowPhysicsWasmEngine {
        constructor() {
            this.instance = null;
            this.exports = null;
            this.memory = null;
            this.isReady = false;
            this._initViews();
            this.init();
        }

        init() {
            try {
                if (typeof WebAssembly === 'undefined') {
                    console.warn('[BrowPhysicsWasm] WebAssembly not supported in this browser.');
                    return;
                }
                const binary = typeof Buffer !== 'undefined'
                    ? Buffer.from(WASM_BASE64, 'base64')
                    : Uint8Array.from(atob(WASM_BASE64), c => c.charCodeAt(0));
                
                const module = new WebAssembly.Module(binary);
                this.instance = new WebAssembly.Instance(module);
                this.exports = this.instance.exports;
                this.memory = this.exports.memory;
                this._initViews();
                this.isReady = true;
                console.log('[BrowPhysicsWasm] Zero-GC WASM Acceleration Engine active (Broadphase + Batch Physics).');
            } catch (err) {
                console.error('[BrowPhysicsWasm] Initialization error:', err);
                this.isReady = false;
            }
        }

        _initViews() {
            if (!this.exports || !this.exports.memory) return;
            const exp = this.exports;
            const mem = exp.memory.buffer;

            // Pedestrian separation buffers
            if (exp.get_ped_x_ptr) {
                this.pedX = new Float32Array(mem, exp.get_ped_x_ptr(), 128);
                this.pedZ = new Float32Array(mem, exp.get_ped_z_ptr(), 128);
                this.pedSepX = new Float32Array(mem, exp.get_ped_sep_x_ptr(), 128);
                this.pedSepZ = new Float32Array(mem, exp.get_ped_sep_z_ptr(), 128);
                this.pedActive = new Uint8Array(mem, exp.get_ped_active_ptr(), 128);
            }

            // Vehicle separation buffers
            if (exp.get_veh_x_ptr) {
                this.vehX = new Float32Array(mem, exp.get_veh_x_ptr(), 128);
                this.vehZ = new Float32Array(mem, exp.get_veh_z_ptr(), 128);
                this.vehSpeed = new Float32Array(mem, exp.get_veh_speed_ptr(), 128);
                this.vehLength = new Float32Array(mem, exp.get_veh_length_ptr(), 128);
                this.vehHp = new Float32Array(mem, exp.get_veh_hp_ptr(), 128);
                this.vehActive = new Uint8Array(mem, exp.get_veh_active_ptr(), 128);
            }
        }

        isEnabled() {
            if (typeof window !== 'undefined' && window.BrowSettings && typeof window.BrowSettings.get === 'function') {
                return window.BrowSettings.get('wasmAcceleration') !== false;
            }
            return true;
        }

        createWorld(colliders, cell = 16) {
            if (!this.isEnabled() || !this.isReady || !this.exports) {
                return null; // Fallback to pure JS physics loop
            }

            const self = this;
            const exp = this.exports;
            exp.reset();
            const num = colliders.length;
            exp.set_num_colliders(num);

            for (let i = 0; i < num; i++) {
                const c = colliders[i];
                exp.set_collider(i, c.x, c.y, c.z, c.sx, c.sy, c.sz);
            }
            exp.build_grid();

            return {
                isWasm: true,
                colliders: colliders,
                cell: cell,
                engine: self,

                queryCircle(x, z, r, out) {
                    out.length = 0;
                    const count = exp.query_circle(x, z, r);
                    for (let i = 0; i < count; i++) {
                        out.push(exp.get_result(i));
                    }
                    return out;
                },

                resolveCircle(pos, r, yBottom, yTop, out) {
                    const hitId = exp.resolve_circle(pos.x, pos.z, r, yBottom, yTop);
                    pos.x = exp.get_out_pos_x();
                    pos.z = exp.get_out_pos_z();
                    if (hitId >= 0 && hitId < colliders.length) {
                        return colliders[hitId];
                    }
                    return null;
                },

                groundAt(x, z, fromY, step, out, LandMask) {
                    const top = exp.ground_at(x, z, fromY, step);
                    const land = (LandMask && LandMask.inside && LandMask.inside(x, z)) ? 0.1 : -0.35;
                    if (top > -900.0) {
                        return Math.max(top, land);
                    }
                    return land;
                },

                /**
                 * Batch Pedestrian Pairwise Separation in WASM
                 * Replaces O(N^2) double loop in JS with a single vectorized microsecond pass
                 */
                batchSolvePedSeparation(peds, px, pz) {
                    if (!exp.batch_solve_ped_separation || !self.pedX) return false;
                    const count = Math.min(peds.length, 128);
                    const pxBuf = self.pedX, pzBuf = self.pedZ, actBuf = self.pedActive;
                    const sepX = self.pedSepX, sepZ = self.pedSepZ;

                    for (let i = 0; i < count; i++) {
                        const p = peds[i];
                        if (p.state === 'dead') {
                            actBuf[i] = 0;
                        } else {
                            actBuf[i] = 1;
                            pxBuf[i] = p.x;
                            pzBuf[i] = p.z;
                        }
                    }

                    exp.batch_solve_ped_separation(count, px, pz);

                    for (let i = 0; i < count; i++) {
                        if (actBuf[i] === 1) {
                            peds[i].sepX = sepX[i];
                            peds[i].sepZ = sepZ[i];
                        } else {
                            peds[i].sepX = 0;
                            peds[i].sepZ = 0;
                        }
                    }
                    return true;
                },

                /**
                 * Batch Vehicle Separation & Collision in WASM
                 * Replaces O(M^2) double loop in JS with an ultra-fast WASM linear memory pass
                 */
                batchSolveVehicleSeparation(vehicles) {
                    if (!exp.batch_solve_vehicle_separation || !self.vehX) return false;
                    const count = Math.min(vehicles.length, 128);
                    const vx = self.vehX, vz = self.vehZ, vsp = self.vehSpeed;
                    const vlen = self.vehLength, vhp = self.vehHp, vact = self.vehActive;

                    for (let i = 0; i < count; i++) {
                        const v = vehicles[i];
                        if (v.dead) {
                            vact[i] = 0;
                        } else {
                            vact[i] = 1;
                            vx[i] = v.x;
                            vz[i] = v.z;
                            vsp[i] = v.speed;
                            vlen[i] = v.spec ? v.spec.L : 4.5;
                            vhp[i] = v.hp;
                        }
                    }

                    exp.batch_solve_vehicle_separation(count);

                    for (let i = 0; i < count; i++) {
                        if (vact[i] === 1) {
                            const v = vehicles[i];
                            v.x = vx[i];
                            v.z = vz[i];
                            v.speed = vsp[i];
                            v.hp = vhp[i];
                        }
                    }
                    return true;
                }
            };
        }

        /**
         * Benchmark comparing JavaScript vs WASM for 100,000 queries
         */
        runBenchmark(iterations = 100000) {
            if (!this.isReady) return { error: 'WASM not ready' };
            const exp = this.exports;

            // Setup a mock scene with 1,500 building colliders
            exp.reset();
            const N = 1500;
            exp.set_num_colliders(N);
            const jsColliders = [];
            for (let i = 0; i < N; i++) {
                const x = (i % 35) * 30.0;
                const z = Math.floor(i / 35) * 30.0;
                exp.set_collider(i, x, 10.0, z, 15.0, 20.0, 15.0);
                jsColliders.push({ x, y: 10.0, z, sx: 15.0, sy: 20.0, sz: 15.0 });
            }
            exp.build_grid();

            // 1. Benchmark WASM
            const t0 = performance.now();
            for (let i = 0; i < iterations; i++) {
                const qx = (i * 7.3) % 1000;
                const qz = (i * 13.7) % 1200;
                exp.resolve_circle(qx, qz, 1.2, 0.0, 2.0);
            }
            const wasmTime = performance.now() - t0;

            // 2. Benchmark JS
            const cell = 16;
            const grid = new Map();
            for (let i = 0; i < jsColliders.length; i++) {
                const c = jsColliders[i];
                const x0 = Math.floor((c.x - c.sx / 2) / cell), x1 = Math.floor((c.x + c.sx / 2) / cell);
                const z0 = Math.floor((c.z - c.sz / 2) / cell), z1 = Math.floor((c.z + c.sz / 2) / cell);
                for (let gx = x0; gx <= x1; gx++) {
                    for (let gz = z0; gz <= z1; gz++) {
                        const key = gx * 100000 + gz;
                        let bucket = grid.get(key);
                        if (!bucket) { bucket = []; grid.set(key, bucket); }
                        bucket.push(i);
                    }
                }
            }
            const out = [];
            const pos = { x: 0, z: 0 };
            const t1 = performance.now();
            for (let i = 0; i < iterations; i++) {
                pos.x = (i * 7.3) % 1000;
                pos.z = (i * 13.7) % 1200;
                for (let iter = 0; iter < 2; iter++) {
                    out.length = 0;
                    const r = 1.8;
                    const x0 = Math.floor((pos.x - r) / cell), x1 = Math.floor((pos.x + r) / cell);
                    const z0 = Math.floor((pos.z - r) / cell), z1 = Math.floor((pos.z + r) / cell);
                    for (let gx = x0; gx <= x1; gx++) {
                        for (let gz = z0; gz <= z1; gz++) {
                            const bucket = grid.get(gx * 100000 + gz);
                            if (!bucket) continue;
                            for (let k = 0; k < bucket.length; k++) {
                                if (out.indexOf(bucket[k]) === -1) out.push(bucket[k]);
                            }
                        }
                    }
                }
            }
            const jsTime = performance.now() - t1;

            return {
                iterations,
                wasmTimeMs: parseFloat(wasmTime.toFixed(2)),
                jsTimeMs: parseFloat(jsTime.toFixed(2)),
                speedup: parseFloat((jsTime / Math.max(0.1, wasmTime)).toFixed(2)),
                wasmMips: parseFloat((iterations / (wasmTime / 1000) / 1000000).toFixed(2))
            };
        }
    }

    root.BrowPhysicsWasm = new BrowPhysicsWasmEngine();
})(typeof window !== 'undefined' ? window : globalThis);
